package com.dangdang.reader.request;

/**
 * 接口请求通过handler传递数据时Message的what定义
 * 
 * @author xiaruri
 * 
 */
public interface RequestConstants {

	String ACTION_MULTI = "multiAction";
	String ACTION_MULTI_V2 = "multiActionV2";
	String CHARSET_NAME_UTF_8 = "UTF-8";

	String ACTION_NEARBY_SEARCH = "nearbySearch";
	String ACTION_NEARBY_CLEAR_LOCATION = "nearbyClearLocation";
	String ACTION_GETLOTTERY_RESULT = "getLotteryResultWithBell";
	String ACTION_RECEIVED_OR_CANCEL = "recivedOrCancelPrize";
	String ACTION_GET_CLIEN_INFO="getClienInfo";

	int MSG_WHAT_REQUEST_DATA_SUCCESS = 101;
	int MSG_WHAT_REQUEST_DATA_FAIL = 102;
	int MSG_WHAT_DELETE_CART_SUCCESS = 103;
	int MSG_WHAT_DELETE_CART_FAIL = 104;
	int MSG_WHAT_UPDATE_CART_SUCCESS = 105;
	int MSG_WHAT_UPDATE_CART_FAIL = 106;
	int MSG_WHAT_CHECK_OR_UNCHECK_ITEM_CART_SUCCESS = 107;
	int MSG_WHAT_CHECK_OR_UNCHECK_ITEM_CART_FAIL = 108;
	int MSG_WHAT_SAVE_SHIP_TYPE_SUCCESS = 109;
	int MSG_WHAT_SAVE_SHIP_TYPE_FAIL = 110;
	int MSG_WHAT_GET_HTML_DATA_SUCCESS = 111;
	int MSG_WHAT_GET_HTML_DATA_FAIL = 112;
	int MSG_WHAT_BIND_USER_MONTHLY_FORFIRST_SHARE_SUCCESS = 209;
	int MSG_WHAT_BIND_USER_MONTHLY_FORFIRST_SHARE_FAIL = 210;


    /**
     * 获取启动图版本
     */
    int MSG_WHAT_BOOT_VERSION = 401;
    int MSG_WHAT_BOOT_BITMAP = 402;
    /**
     * 获取im信息
     */
    int MSG_WHAT_GET_IMUSER_SUCCESS = 501;
    int MSG_WHAT_GET_IMUSER_FAILED = 502;
    int MSG_WHAT_ADD_FRIEND_SUCCESS = 503;
    int MSG_WHAT_ADD_FRIEND_FAILED = 504;
    int MSG_WHAT_CANCEL_FRIEND_SUCCESS = 505;
    int MSG_WHAT_CANCEL_FRIEND_FAILED = 506;
    int MSG_WHAT_GET_FRIEND_SUCCESS = 507;
    int MSG_WHAT_GET_FRIEND_FAILED = 508;
    int MSG_WHAT_SEARCH_FRIEND_SUCCESS = 509;
    int MSG_WHAT_SEARCH_FRIEND_FAILED = 510;
    int MSG_WHAT_GET_BUYALSOBUY_SUCCESS = 511;
    int MSG_WHAT_GET_BUYALSOBUY_FAILED = 512;

	int COMMENT_SOURCE_BAR = 1000;
	int COMMENT_SOURCE_FANPIANER = 2000;
	int COMMENT_SOURCE_PREEMPTIVE = 3000;
	int COMMENT_SOURCE_CHANNEL = 4000;
	int COMMENT_SOURCE_CHANNEL_STRATEGY = 7000;
	
	int MSG_WHAT_JUMP_BOOK_DETAIL = 601; // 跳单品
	int MSG_WHAT_JUMP_CHANNEL_BOOK = 602; // 跳频道书单
	int MSG_WHAT_JUMP_CHANNEL_DETAIL = 603; // 跳频道详情
	int MSG_WHAT_JUMP_ARTICLE = 604; // 跳频道, 翻篇儿, 抢鲜读的文章
	int MSG_WHAT_JUMP_BAR = 605; // 跳书吧
	int MSG_WHAT_JUMP_BAR_ARTICLE = 606; // 跳书吧的文章
	int MSG_WHAT_JUMP_STORE_DISSERTATION = 607; // 跳专题
}
